// Even Fibonacci numbers

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let sum = 0;
let first = 0;
let next = 1;
let evenValueSum = 0;

while (sum < 4000000) {
    sum = first + next;
    first = next;
    next = sum;
    if (sum % 2 === 0) {
        evenValueSum += sum;
    }
}

console.log(evenValueSum);